name: Public build

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Write maven configuration
        run: |
          mkdir -p $HOME/.gradle


          echo <<EOF > $HOME/.gradle/gradle.properties
          mavenUser=actions
          mavenPassword=${{ secrets.GITHUB_TOKEN }}
          EOF
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        run: ./gradlew publish
